/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.encuestas_app.vistas.admin;

import com.mycompany.encuestas_app.services.UsuarioService;
import com.mycompany.encuestas_app.vistas.admin.MenuAdminFrame;
import com.mycompany.encuestas_app.vistas.admin.MenuAdminFrame;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import modelos.Usuario;
import org.mindrot.jbcrypt.BCrypt;

/**
 *
 * @author alexpy
 */
public class AgregarAdministradorFrame extends javax.swing.JFrame {
        
        private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(AgregarAdministradorFrame.class.getName());
        
        public UsuarioService service = new UsuarioService();
        
        /**
         * Creates new form agregarAdministradorFrame
         */
        public AgregarAdministradorFrame() {
                initComponents();
                
                setLocationRelativeTo(null);
        
        }

        /**
         * This method is called from within the constructor to initialize the
         * form. WARNING: Do NOT modify this code. The content of this method is
         * always regenerated by the Form Editor.
         */
        @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                jLabel1 = new javax.swing.JLabel();
                jPanel1 = new javax.swing.JPanel();
                jLabel3 = new javax.swing.JLabel();
                ent_username = new javax.swing.JTextField();
                ent_email = new javax.swing.JTextField();
                ent_password = new javax.swing.JPasswordField();
                btnContinuar = new javax.swing.JButton();
                btnRegresar = new javax.swing.JButton();

                setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

                jLabel1.setFont(new java.awt.Font("Liberation Sans", 1, 80)); // NOI18N
                jLabel1.setForeground(new java.awt.Color(0, 153, 204));
                jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                jLabel1.setText("EncuestApp");

                jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
                jPanel1.setForeground(new java.awt.Color(255, 255, 255));

                jLabel3.setBackground(new java.awt.Color(204, 204, 204));
                jLabel3.setFont(new java.awt.Font("Liberation Sans", 0, 48)); // NOI18N
                jLabel3.setForeground(new java.awt.Color(0, 0, 0));
                jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                jLabel3.setText("Agregar Admin");

                ent_username.setFont(new java.awt.Font("Liberation Sans", 0, 36)); // NOI18N
                ent_username.setBorder(javax.swing.BorderFactory.createTitledBorder("Nombre de usuario"));
                ent_username.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                ent_usernameActionPerformed(evt);
                        }
                });

                ent_email.setFont(new java.awt.Font("Liberation Sans", 0, 36)); // NOI18N
                ent_email.setBorder(javax.swing.BorderFactory.createTitledBorder("Email"));
                ent_email.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                ent_emailActionPerformed(evt);
                        }
                });

                ent_password.setFont(new java.awt.Font("Liberation Sans", 0, 36)); // NOI18N
                ent_password.setBorder(javax.swing.BorderFactory.createTitledBorder("Contraseña"));

                btnContinuar.setBackground(new java.awt.Color(0, 102, 255));
                btnContinuar.setFont(new java.awt.Font("Liberation Sans", 1, 36)); // NOI18N
                btnContinuar.setForeground(new java.awt.Color(255, 255, 255));
                btnContinuar.setText("Agregar");
                btnContinuar.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnContinuarActionPerformed(evt);
                        }
                });

                javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
                jPanel1.setLayout(jPanel1Layout);
                jPanel1Layout.setHorizontalGroup(
                        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(0, 16, Short.MAX_VALUE)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                                        .addComponent(ent_email)
                                                                        .addComponent(ent_password, javax.swing.GroupLayout.DEFAULT_SIZE, 450, Short.MAX_VALUE)
                                                                        .addComponent(ent_username))
                                                                .addGap(15, 15, 15))
                                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                                .addComponent(btnContinuar)
                                                                .addGap(135, 135, 135))))
                                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 481, Short.MAX_VALUE)))
                );
                jPanel1Layout.setVerticalGroup(
                        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jLabel3)
                                .addGap(43, 43, 43)
                                .addComponent(ent_username, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(ent_email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(ent_password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(43, 43, 43)
                                .addComponent(btnContinuar, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(47, Short.MAX_VALUE))
                );

                btnRegresar.setBackground(new java.awt.Color(204, 51, 0));
                btnRegresar.setFont(new java.awt.Font("Liberation Sans", 1, 36)); // NOI18N
                btnRegresar.setForeground(new java.awt.Color(255, 255, 255));
                btnRegresar.setText("Regresar");
                btnRegresar.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnRegresarActionPerformed(evt);
                        }
                });

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                getContentPane().setLayout(layout);
                layout.setHorizontalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1388, Short.MAX_VALUE)
                                                .addContainerGap())
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addGap(0, 0, Short.MAX_VALUE)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(454, 454, 454))
                                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                                .addComponent(btnRegresar)
                                                                .addGap(594, 594, 594))))))
                );
                layout.setVerticalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel1)
                                .addGap(40, 40, 40)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(49, 49, 49)
                                .addComponent(btnRegresar, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(54, Short.MAX_VALUE))
                );

                pack();
        }// </editor-fold>//GEN-END:initComponents

        private void ent_usernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ent_usernameActionPerformed
                // TODO add your handling code here:
        }//GEN-LAST:event_ent_usernameActionPerformed

        private void ent_emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ent_emailActionPerformed
                // TODO add your handling code here:
        }//GEN-LAST:event_ent_emailActionPerformed

        private void btnContinuarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnContinuarActionPerformed

                // Conseguir datos
    String username = ent_username.getText().trim();
    String email = ent_email.getText().trim();
    String password = new String(ent_password.getPassword()).trim(); // si es JPasswordField, mejor así

    // Validar datos
    String errores = "";

    if (username.isEmpty() || email.isEmpty() || password.isEmpty()) {
        errores += "-Ingrese todos los datos";
    }

    // Validar espacios en username
    for (int i = 0; i < username.length(); i++) {
        char u = username.charAt(i);
        if (u == ' ') {
            errores += "\n-No use espacio entre el nombre";
            break;
        }
    }

    // Validar email básico
    int arroba = 0;
    boolean tienePunto = false;
    OUTER:
    for (int i = 0; i < email.length(); i++) {
        char u = email.charAt(i);
        switch (u) {
            case ' ' -> {
                errores += "\n-No use espacio entre el email";
                break OUTER;
            }
            case '@' -> arroba++;
            case '.' -> tienePunto = true;
            default -> {
            }
        }
    }
    if (arroba != 1 || !tienePunto) {
        errores += "\n-Use un formato de email";
    }

    // Validar contraseña
    if (password.length() < 5) {
        errores += "\n-Ingrese una contraseña con al menos 5 caracteres";
    }

    for (int i = 0; i < password.length(); i++) {
        char u = password.charAt(i);
        if (u == ' ') {
            errores += "\n-No use espacio entre la contraseña";
            break;
        }
    }

    // Validar existencia por nombre y email
    try {
        Usuario usuarioPorNombre = service.getUsuarioPorNombre(username);
        if (usuarioPorNombre != null) {
            errores += "\n-Nombre de usuario ya en uso";
        }

        // Solo si tienes este método en tu service
        Usuario usuarioPorEmail = service.getUsuarioPorEmail(email);
        if (usuarioPorEmail != null) {
            errores += "\n-Email ya en uso";
        }

    } catch (Exception ex) {
        System.getLogger(AgregarAdministradorFrame.class.getName())
              .log(System.Logger.Level.ERROR, (String) null, ex);
        JOptionPane.showMessageDialog(null, "Error al validar existencia del usuario");
        return;
    }

    // Si hay errores, mostrarlos y limpiar campos
    if (!errores.isEmpty()) {
        ent_username.setText("");
        ent_email.setText("");
        ent_password.setText("");
        JOptionPane.showMessageDialog(null, errores);
        return;
    }

    // Hashear contraseña con BCrypt
    String passwordHash = BCrypt.hashpw(password, BCrypt.gensalt());

    // Crear usuario admin con contraseña hasheada
    Usuario user = new Usuario(username, email, passwordHash, true);

    try {
        service.addUsr(user, ent_password.getText());
    } catch (Exception ex) {
        System.getLogger(AgregarAdministradorFrame.class.getName())
              .log(System.Logger.Level.ERROR, (String) null, ex);
        JOptionPane.showMessageDialog(null, "Error al guardar usuario");
        return;
    }

    System.out.println("cuenta creada (admin)");
    new MenuAdminFrame().setVisible(true);
    this.dispose();

        }//GEN-LAST:event_btnContinuarActionPerformed

        private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
                new MenuAdminFrame().setVisible(true);
                this.dispose();
        }//GEN-LAST:event_btnRegresarActionPerformed


        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JButton btnContinuar;
        private javax.swing.JButton btnRegresar;
        private javax.swing.JTextField ent_email;
        private javax.swing.JPasswordField ent_password;
        private javax.swing.JTextField ent_username;
        private javax.swing.JLabel jLabel1;
        private javax.swing.JLabel jLabel3;
        private javax.swing.JPanel jPanel1;
        // End of variables declaration//GEN-END:variables
}
